eid=6006
rating=4.5
ename="Pavan"
c=10+20j
avail=True
l=[10,20.5,"Pavan"]
t=(10,20,30,40)
s={10,20,30,10}
d={'eid':101,'ename':"Pavan"}
b=bytes([10,20,30])
ba=bytearray(b)
r=range(10)
fs=frozenset(s)

def calc():
    pass

print(eid)
print(type(eid))
print(rating)
print(type(rating))
print(ename)
print(type(ename))
print(c)
print(type(c))
print(avail)
print(type(avail))
print(l)
print(type(l))
print(t)
print(type(t))
print(s)
print(type(s))
print(d)
print(type(d))
print(b)
print(type(b))
print(ba)
print(type(ba))
print(r)
print(type(r))
print(fs)
print(type(fs))
print(calc())
print(type(calc()))
